### ISSUE TITLE
Bubble, Selection, and Shell don't have time delays internal

### ISSUE THREAD

**Issue by Sprogel** [Sprogel/Musical-Sorting#11]
TimeDelay is unused, you need to call
    Thread.sleep(timeDelay)
once per iteration.

```
try{
    Thread.sleep(delay);
  }catch(InterruptedException e){
    Log.w(SORT_NAME_TAG, "Unable to pause Radix Sort.\n" + e.toString() );
  } // end try catch
```

Name SORT_NAME_TAG the name of the sort, eg SHELL_SORT, set it as a final string, and make it equal the sort name plus tag.
eg for Radix Sort:

```
private final String RADIX_SORT_TAG = "Radix Sort";
```

**Comment by somethingShiny** [comment]
I probably should have remembered to close this when I did it.
