### ISSUE TITLE
Need Backlogs

### ISSUE THREAD

**Issue by Aeirdnom** [Sprogel/Musical-Sorting#12]
I need backlogs and other information if we want this powerpoint done by tomorrow. The more info you can give me, the more I can do.

**Comment by somethingShiny** [comment]
Backlogs have been emailed to you. Basically anything in the sprint backlogs can be switched out for another weeks backlogs and we lost the fourth member in the middle of working on sprint 2.

**Comment by Aeirdnom** [comment]
Thanks. In the process of making the basic powerpoint now. Will e-mail it to both of you when I finish with what I have for review.
