### ISSUE TITLE
Upload your sorting classes

### ISSUE THREAD

**Issue by Sprogel** [Sprogel/Musical-Sorting#2]
I'm to the point where I can't do much more without a class to test it with.

**Comment by Sprogel** [comment]
Update: Radix and Bogo (wasn't @somethingShiny doing Bogo? Ohh well) have been included, but not integrated. I'll get to that tomorrow and start testing if the backed actually works...

Here's to working on the first time hopes.

**Comment by Aeirdnom** [comment]
That'd be awesome if it did. Also, I'm pretty sure @somethingShiny has Bubble, is what you're thinking of.
